// LoRa
Blockly.Msg.WEBDUINO_LORA_SEND_STRING = "传送字符串";
Blockly.Msg.WEBDUINO_LORA_SUCCESS_CALLBACK = "成功后执行";
Blockly.Msg.WEBDUINO_LORA_FAIL_CALLBACK = "失败后执行";
Blockly.Msg.WEBDUINO_LORA_RECEIVE_CALLBACK = "接收字符串后执行";
Blockly.Msg.WEBDUINO_LORA_RECEIVED_STRING = "接收的字符串";