Blockly.Msg.WEBDUINO_PHOTOCELL = "光敏电阻";
Blockly.Msg.WEBDUINO_PHOTOCELL_UPPER_LEFT = "左上";
Blockly.Msg.WEBDUINO_PHOTOCELL_UPPER_RIGHT = "右上";
Blockly.Msg.WEBDUINO_PHOTOCELL_DETECTED = "开始检测";
Blockly.Msg.WEBDUINO_PHOTOCELL_PIN = "光敏腳位";
Blockly.Msg.WEBDUINO_PHOTOCELL_DO = "执行";
Blockly.Msg.WEBDUINO_PHOTOCELL_VAL = "检测的数值";
Blockly.Msg.WEBDUINO_PHOTOCELL_STOP = "停止检测";
