// CarTracker
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_1 = "设置信号为 ○○ 时，自走车";
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_2 = "设置信号为 ○● 时，自走车";
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_3 = "设置信号为 ●○ 时，自走车";
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_4 = "设置信号为 ●● 时，自走车";
Blockly.Msg.WEBDUINO_CARTRACKER_DO = "执行";
Blockly.Msg.WEBDUINO_CARTRACKER_ON = "启动循迹";
Blockly.Msg.WEBDUINO_CARTRACKER_OFF = "停止循迹";
Blockly.Msg.WEBDUINO_CARTRACKER_STOP = "停止";
Blockly.Msg.WEBDUINO_CARTRACKER_FORWARD = "前进";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_LEFT = "原地左转";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_RIGHT = "原地右转";
Blockly.Msg.WEBDUINO_CARTRACKER_BACK = "后退";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_FORWARD = "左前";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_FORWARD = "右前";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_BACK = "左后";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_BACK = "右后";
Blockly.Msg.WEBDUINO_CARTRACKER_KEEP = "保持不变";

Blockly.Msg.WEBDUINO_TOYCAR = "自走车";
Blockly.Msg.WEBDUINO_TOYCAR_ACTION = "自走车动作";
Blockly.Msg.WEBDUINO_TOYCAR_GOFRONT = "前进";
Blockly.Msg.WEBDUINO_TOYCAR_GOBACK = "后退";
Blockly.Msg.WEBDUINO_TOYCAR_GOLEFT = "左前";
Blockly.Msg.WEBDUINO_TOYCAR_GORIGHT = "右前";
Blockly.Msg.WEBDUINO_TOYCAR_BACKLEFT = "左后";
Blockly.Msg.WEBDUINO_TOYCAR_BACKRIGHT = "右后";
Blockly.Msg.WEBDUINO_TOYCAR_TURNRIGHT = "原地右转";
Blockly.Msg.WEBDUINO_TOYCAR_TURNLEFT = "原地左转";
Blockly.Msg.WEBDUINO_TOYCAR_STOP = "停止";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED = "速度"
Blockly.Msg.WEBDUINO_TOYCAR_ALL_WHEEL = "两轮";
Blockly.Msg.WEBDUINO_TOYCAR_RIGHT_WHEEL = "右轮";
Blockly.Msg.WEBDUINO_TOYCAR_LEFT_WHEEL = "左轮";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_FASTEST = "最快";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_FASTER = "快";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_MEDIUM = "中";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_SLOW = "慢";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_SLOWEST = "很慢";

Blockly.Msg.WEBDUINO_CARBUTTON_EVENT_WHEN = "当小车按钮被";

Blockly.Msg.WEBDUINO_ULTRASONIC_DISTANCE = "超音波传感器所截取的距离 ( 公分 )";

Blockly.Msg.WEBDUINO_IRRECV_ON = "红外线开始接收信号";
Blockly.Msg.WEBDUINO_IRRECV_DO = "执行";
Blockly.Msg.WEBDUINO_IRRECV_CODE = "红外线接收的代码";
Blockly.Msg.WEBDUINO_IRLED_LAUNCHCODE = "红外线发射代码 ( 十六进位 )";

Blockly.Msg.WEBDUINO_WS2812_LED_SET = "设定 LED 灯环";
Blockly.Msg.WEBDUINO_WS2812_LED_COLOR = "颗颜色为";
Blockly.Msg.WEBDUINO_WS2812_DISPLAY = "显示";
Blockly.Msg.WEBDUINO_WS2812_BRIGHTBESS = "设定灯环亮度 (0~100)";
Blockly.Msg.WEBDUINO_WS2812_CLOSE = "关闭灯环";

Blockly.Msg.WEBDUINO_TCS34725_COLOR = "颜色传感器测得";
Blockly.Msg.WEBDUINO_TCS34725_BLACK = "黑色";
Blockly.Msg.WEBDUINO_TCS34725_BLUE = "蓝色";
Blockly.Msg.WEBDUINO_TCS34725_GREEN = "绿色";
Blockly.Msg.WEBDUINO_TCS34725_CYAN = "青色";
Blockly.Msg.WEBDUINO_TCS34725_RED = "红色";
Blockly.Msg.WEBDUINO_TCS34725_PURPLE = "紫色";
Blockly.Msg.WEBDUINO_TCS34725_YELLOW = "黄色";
Blockly.Msg.WEBDUINO_TCS34725_WHITE = "白色";
