// CarTracker
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_1 = "設定訊號為 ○○ 時，自走車";
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_2 = "設定訊號為 ○● 時，自走車";
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_3 = "設定訊號為 ●○ 時，自走車";
Blockly.Msg.WEBDUINO_CARTRACKER_STATUS_4 = "設定訊號為 ●● 時，自走車";
Blockly.Msg.WEBDUINO_CARTRACKER_DO = "執行";
Blockly.Msg.WEBDUINO_CARTRACKER_ON = "啟動循跡";
Blockly.Msg.WEBDUINO_CARTRACKER_OFF = "停止循跡";
Blockly.Msg.WEBDUINO_CARTRACKER_STOP = "停止";
Blockly.Msg.WEBDUINO_CARTRACKER_FORWARD = "前進";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_LEFT = "原地左轉";
Blockly.Msg.WEBDUINO_CARTRACKER_TURN_RIGHT = "原地右轉";
Blockly.Msg.WEBDUINO_CARTRACKER_BACK = "後退";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_FORWARD = "左前";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_FORWARD = "右前";
Blockly.Msg.WEBDUINO_CARTRACKER_LEFT_BACK = "左後";
Blockly.Msg.WEBDUINO_CARTRACKER_RIGHT_BACK = "右後";
Blockly.Msg.WEBDUINO_CARTRACKER_KEEP = "保持不變";

Blockly.Msg.WEBDUINO_TOYCAR = "自走車";
Blockly.Msg.WEBDUINO_TOYCAR_ACTION = "自走車動作";
Blockly.Msg.WEBDUINO_TOYCAR_GOFRONT = "前進";
Blockly.Msg.WEBDUINO_TOYCAR_GOBACK = "後退";
Blockly.Msg.WEBDUINO_TOYCAR_GOLEFT = "左前";
Blockly.Msg.WEBDUINO_TOYCAR_GORIGHT = "右前";
Blockly.Msg.WEBDUINO_TOYCAR_BACKLEFT = "左後";
Blockly.Msg.WEBDUINO_TOYCAR_BACKRIGHT = "右後";
Blockly.Msg.WEBDUINO_TOYCAR_TURNRIGHT = "原地右轉";
Blockly.Msg.WEBDUINO_TOYCAR_TURNLEFT = "原地左轉";
Blockly.Msg.WEBDUINO_TOYCAR_STOP = "停止";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED = "速度";
Blockly.Msg.WEBDUINO_TOYCAR_ALL_WHEEL = "兩輪";
Blockly.Msg.WEBDUINO_TOYCAR_RIGHT_WHEEL = "右輪";
Blockly.Msg.WEBDUINO_TOYCAR_LEFT_WHEEL = "左輪";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_FASTEST = "最快";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_FASTER = "快";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_MEDIUM = "中";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_SLOW = "慢";
Blockly.Msg.WEBDUINO_TOYCAR_SPEED_SLOWEST = "很慢";

Blockly.Msg.WEBDUINO_CARBUTTON_EVENT_WHEN = "當小車按鈕被";

Blockly.Msg.WEBDUINO_ULTRASONIC_DISTANCE = "超音波傳感器所擷取的距離 ( 公分 )";

Blockly.Msg.WEBDUINO_IRRECV_ON = "當紅外線接收到訊號";
Blockly.Msg.WEBDUINO_IRRECV_DO = "執行";
Blockly.Msg.WEBDUINO_IRRECV_CODE = "紅外線接收的代碼";
Blockly.Msg.WEBDUINO_IRLED_LAUNCHCODE = "紅外線發射代碼 ( 十六進位 )";

Blockly.Msg.WEBDUINO_WS2812_LED_SET = "設定魔幻 LED 第";
Blockly.Msg.WEBDUINO_WS2812_LED_COLOR = "顆顏色為";
Blockly.Msg.WEBDUINO_WS2812_DISPLAY = "顯示";
Blockly.Msg.WEBDUINO_WS2812_BRIGHTBESS = "設定魔幻 LED 亮度 (0~100)";
Blockly.Msg.WEBDUINO_WS2812_CLOSE = "關閉魔幻 LED ";
