Blockly.Msg.WEBDUINO_THERMISTOR = "热敏电阻";
Blockly.Msg.WEBDUINO_THERMISTOR_DETECTED = "开始侦测";
Blockly.Msg.WEBDUINO_THERMISTOR_DO = "执行";
Blockly.Msg.WEBDUINO_THERMISTOR_PIN = "熱敏腳位";  
Blockly.Msg.WEBDUINO_THERMISTOR_VAL = "目前温度";
Blockly.Msg.WEBDUINO_THERMISTOR_STOP = "停止侦测";
